In [ ]:
1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [83]:
import numpy as np
import collections as col
arr = np.random.randint(1,10,10)
print(col.Counter(arr.flatten()))


Counter({5: 3, 9: 2, 7: 2, 3: 2, 6: 1})


In [5]:
counts_elements = np.unique(arr, return_counts=True)

In [6]:
counts_elements

(array([2, 5, 7, 8, 9]), array([1, 3, 1, 3, 2], dtype=int64))

In [ ]:
2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.


In [7]:
array=np.random.randint(0,9,9)
print(array)
a=np.reshape(array,(3,3))
print(a)

[8 1 7 7 5 7 7 8 4]
[[8 1 7]
 [7 5 7]
 [7 8 4]]


In [ ]:
3. How to find the memory size of any array

In [17]:
array=np.random.randint(99,size=(10,10))
array.nbytes

400

In [ ]:
4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [15]:
data=np.ones((10,10))
data[1:-1,1:-1]=0
print(data)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [19]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
6. Normalize a 5x5 random matrix.
normalization formula : ((a-mean(a))/std(a))

In [20]:
a= np.random.random((3,3))
normzed = (a-np.mean(a))/  np.std(a)
normzed

array([[ 0.3332906 , -0.4594859 ,  0.71798469],
       [-1.13431192, -0.97543087,  2.25828206],
       [ 0.11487478,  0.04432973, -0.89953318]])

In [ ]:
7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [85]:
arry = np.arange(0,11,10)
arry

In [31]:
new = [np.where(np.logical_and(arry>=3, arry<=8))]
np.negative(new)

array([[[-3, -4, -5, -6, -7, -8]]], dtype=int64)

In [ ]:
8. How to get the dates of yesterday, today and tomorrow?

In [32]:
from datetime import date
from datetime import timedelta
today=date.today()
yesterday=today-timedelta(days=1)
tomorrow=today+timedelta(days=1)
print(yesterday)
print(today)
print(tomorrow)

2020-02-13
2020-02-14
2020-02-15


In [ ]:
9. Generate two arrays of size 2X4 & 3X3, find difference between them.

In [36]:
f_arry = np.random.randint(1,10,(2,4))
s_arry = np.random.randint(1,10,(3,3))
result= f_arry.reshape(1,8) - s_arry.reshape(1,9)


ValueError: operands could not be broadcast together with shapes (1,8) (1,9) 

In [ ]:
10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?
['cat','cat',...,'rat','dog','dog','cat'...]

In [86]:
array1 = np.array(['cat', 'dog', 'rat'])
array2 = np.random.choice(array1, size=100)
print('Generated 100 elements are', array2, sep='\n')

Generated 100 elements are
['dog' 'rat' 'rat' 'dog' 'cat' 'dog' 'cat' 'dog' 'cat' 'cat' 'dog' 'rat'
 'rat' 'cat' 'rat' 'cat' 'cat' 'dog' 'cat' 'cat' 'rat' 'dog' 'dog' 'rat'
 'rat' 'rat' 'dog' 'dog' 'rat' 'dog' 'dog' 'rat' 'dog' 'rat' 'cat' 'dog'
 'dog' 'cat' 'rat' 'dog' 'dog' 'cat' 'rat' 'rat' 'cat' 'rat' 'cat' 'cat'
 'dog' 'cat' 'rat' 'rat' 'dog' 'rat' 'rat' 'rat' 'rat' 'rat' 'cat' 'dog'
 'rat' 'dog' 'dog' 'cat' 'cat' 'rat' 'cat' 'rat' 'cat' 'rat' 'cat' 'cat'
 'cat' 'dog' 'dog' 'dog' 'cat' 'cat' 'cat' 'dog' 'dog' 'rat' 'rat' 'rat'
 'cat' 'rat' 'dog' 'rat' 'dog' 'cat' 'dog' 'dog' 'cat' 'cat' 'rat' 'dog'
 'rat' 'cat' 'dog' 'dog']


In [ ]:
11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [42]:
arr = np.linspace(0,1,12,endpoint=True)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
12. Given a two dimensional array, how to extract unique rows?

In [44]:
arr=np.random.randint(0,2,(3,3))
print(arr)
new_arr=np.unique(arr, axis=0)
print(new_arr)

[[1 0 0]
 [0 1 1]
 [1 1 0]]
[[0 1 1]
 [1 0 0]
 [1 1 0]]


In [ ]:
13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

In [48]:
arry = np.zeros((3,3), [('x',float),('y',float)])
arry['x'], arry['y'] = np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3))
print(arry)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


In [ ]:
14. How to find the closest value (to a given scalar) in a vector

In [57]:
value = 0.5
array = np.random.random(10)
array = np.asarray(array)
idx = (np.abs(array - value)).argmin()
ans = array[idx]
print(array,"value =" ,ans,    value)

[0.41637332 0.80006808 0.62724405 0.59885192 0.78775475 0.25328239
 0.36059609 0.68034217 0.93779347 0.12882358] value = 0.41637331539901123 0.5


In [ ]:
15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [59]:
a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.46505032 0.40155686 0.31527944 0.21476973 0.32215443
  0.29710342 0.1027854  0.43944893 0.21819667]
 [0.46505032 0.         0.82933018 0.42280072 0.64261836 0.61624445
  0.20816407 0.55998364 0.81529438 0.38416671]
 [0.40155686 0.82933018 0.         0.48395457 0.19045346 0.60278058
  0.69298656 0.30045623 0.13342313 0.61010085]
 [0.31527944 0.42280072 0.48395457 0.         0.33834728 0.63096531
  0.39881175 0.33664798 0.4265901  0.45815903]
 [0.21476973 0.64261836 0.19045346 0.33834728 0.         0.46716899
  0.50267964 0.11958323 0.23129394 0.42976223]
 [0.32215443 0.61624445 0.60278058 0.63096531 0.46716899 0.
  0.40852799 0.36007534 0.69161355 0.23354281]
 [0.29710342 0.20816407 0.69298656 0.39881175 0.50267964 0.40852799
  0.         0.39949623 0.70859655 0.17600266]
 [0.1027854  0.55998364 0.30045623 0.33664798 0.11958323 0.36007534
  0.39949623 0.         0.35046335 0.31136646]
 [0.43944893 0.81529438 0.13342313 0.4265901  0.23129394 0.69161355
  0.70859655 0.35046

In [ ]:
16. How to sort an array by the nth column?

In [65]:
arr = np.array([[1,21,3],[5,4,2],[56,12,4]])
arr1 = arr[arr[:,2].argsort()]
print(arr)
print(arr1)

[[ 1 21  3]
 [ 5  4  2]
 [56 12  4]]
[[ 5  4  2]
 [ 1 21  3]
 [56 12  4]]


In [ ]:
17.How to tell if a given 2D array has null columns?

In [72]:
Z = np.random.randint(0,3,(3,10)).astype(float)
Z[:,0] = np.nan
G = np.isnan(Z)
print((G.all(axis=0)).any())

True


In [ ]:
18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [80]:
arry= np.random.randint(1,10,(5,5))
print(arry)
print(np.sum(arry[0:,3:]))

[[3 5 1 1 8]
 [1 8 7 3 1]
 [7 5 7 7 1]
 [4 6 6 3 4]
 [7 8 1 4 6]]
38


In [ ]:
19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [ ]:
arry= np.random.randint(1,100,(5,5))
print(arry)
