In [ ]:
1. Create an array and find sum of it.
Level: Easy

In [19]:
arry = np.random.randint(1,11,(1,11))
sum_a = np.sum(arry)
sum_a

49

In [ ]:
2. Find sin of given array.
Level: Easy

In [20]:
ary = np.array([1,2,3,4,5])
sin_a = np.sin(ary)
sin_a

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
3. Find mean of matrix along row and column.
Level: Easy

In [26]:
data = np.random.randint(1,50,(2,2))
row_mean = data.mean(axis=1)
col_mean = data.mean(axis=0)
print(row_mean,col_mean)

[ 6.5 19.5] [16. 10.]


In [ ]:
4. Find standard deviation of given array.
Level: Easy

In [29]:
arry = np.random.randint(1,15,(1,10))
s_d = np.std(arry)
s_d

3.138470965295043

In [ ]:
5. Create a 3*3 matrix and print it's transpose matrix
Level: Easy

In [33]:
mat = np.random.randint(1,10,(3,3))
mat1 =mat.transpose()
print(mat)
print(mat1)

[[7 2 1]
 [1 2 8]
 [2 3 3]]
[[7 1 2]
 [2 2 3]
 [1 8 3]]


In [ ]:
6. Create an array of 3*3 and find index of max along both axis.¶
Level: Medium

In [36]:
matrix = np.random.randint(1,50,(3,3))
print(matrix)
max_val = matrix.max()
idx = np.where(matrix == max_val)
print(idx)

[[12 24 18]
 [45 14 26]
 [13 38 47]]
(array([2], dtype=int64), array([2], dtype=int64))


In [ ]:
7. find sum of two matrix.
Level: Medium

In [38]:
first_m = np.random.randint(1,11,(2,2))
sec_m = np.random.randint(11,22,(2,2))
sum_1 = np.sum(first_m)
sum_2 = np.sum(sec_m)
total_sum =sum_1+sum_2

In [ ]:
8. Find indexes of max element along axis=0 and axis=1 .
Level: Medium

In [39]:
arr=np.random.randint(1,120,(3,3))
print(arr)
print(np.argmax(arr,axis=0))#col
print(np.argmax(arr,axis=1))#row

[[ 68 104  23]
 [ 77 102  30]
 [ 63  68  74]]
[1 0 2]
[1 1 2]


In [ ]:
9. Write a program to add two arrays of different shape.
Hint: Broadcasting Level: Medium sample input:

In [ ]:
10. Try to solve a array and print a array with indices which would sort the given array.
sample input:

In [40]:
ary=np.array([5,1,7,2])
ind = np.argsort(arr)
print("sorted index of arry",np.argsort(arr))
print("elements of sorted array",ary[ind])

sorted index of arry [[2 0 1]
 [2 0 1]
 [0 1 2]]
elements of sorted array [[7 5 1]
 [7 5 1]
 [5 1 7]]


In [ ]:
11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.
Level: Medium

In [41]:
arr=np.random.randint(1,111,(3,3))
print(arr)
print("Column Indices",np.argsort(arr,axis=0))#column
print("Row Indices",np.argsort(arr,axis=1))#row

[[ 61 102 110]
 [ 10  73  46]
 [ 11  83  66]]
Column Indices [[1 1 1]
 [2 2 2]
 [0 0 0]]
Row Indices [[0 1 2]
 [0 2 1]
 [0 2 1]]


In [ ]:
12. calculate multiplication of transpose and matrix itself of a 3*3 matrix.¶
Level: Medium

In [44]:
simp_arry = np.random.randint(1,200,(3,3))
transpo_arry = simp_arry.transpose()
mul_arr = simp_arry.dot(transpo_arry)
print(transpo_arry)

[[137 159 103]
 [ 43 139  43]
 [162  54  25]]


In [ ]:
13. Find solution for given linear equstion:
2x + 5y = 28 4x + 3*y = 81