In [ ]:
1. Find dot product of two arrays.
a = [2j, 3j],

b = [2j, 3j]

Level: Easy

In [3]:
import numpy as np

a = [2j, 3j]
b = [2j, 3j]
a = np.array(a)
b = np.array(b)
a.dot(b)

(-13+0j)

In [ ]:
2. Create two arrays of 2-D and find dot product of it.

In [4]:
a = np.random.randint(1,100,(3,3))
b = np.random.randint(1,100,(3,3))
a.dot(b)

array([[ 7666, 10265,  8879],
       [ 7488,  6973,  5004],
       [13368, 17801, 13776]])

In [ ]:
3. Find vector product of given array.
a = np.array([1+2j,3+4j])

b = np.array([5+6j,7+8j])

Level: Easy

In [5]:
a = np.array([1+2j,3+4j])

b = np.array([5+6j,7+8j])

print(np.cross(a,b))
print(np.vdot(a,b))

-16j
(70-8j)


In [6]:
a=np.random.randint(100,size=(3,3))
print(a)

[[37 47 65]
 [81 74 35]
 [82 26  8]]


In [ ]:
4. FIrst create given array withound using direct value insted use numpy utlities and then find inner product for given array.
a = [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11]]

b = [[12 13 14 15] [16 17 18 19] [20 21 22 23]]

Level: Easy

In [7]:
a = np.linspace(0,11,12)
b = np.linspace(12,23,12)
a = a.reshape(4,3)
b = b.reshape(4,3)
print(a)
print(b)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]


In [8]:
np.inner(a,b)

array([[ 41.,  50.,  59.,  68.],
       [158., 194., 230., 266.],
       [275., 338., 401., 464.],
       [392., 482., 572., 662.]])

In [ ]:
5. Using given two array try to print out 3rd given array.
a = np.array(['a', 'b', 'c'], dtype=object) b = np.array([1,2,3])

output = [['a', 'aa', 'aaa'], ['b', 'bb', 'bbb'], ['c', 'cc', 'ccc']]

Level: Medium

In [16]:
first_a = np.array(['a', 'b', 'c'], dtype=object) 
second_a = np.array([1,2,3])
# assin = np.multiply(second_a,first_a)
third= first_a.reshape(3,1)*second_a.reshape(1,3)
third

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

In [ ]:
6. Solve the system of equations 3 x0 + x1 = 9 and x0 + 2 x1 = 8
Level: Medium

In [19]:
f_equ = np.array([[3,1],[1,2]])
s_eque = np.array([9,8])
np.linalg.solve(f_equ,s_eque)

array([2., 3.])

In [ ]:
7. Check the following solution is right or wrong uisng numpy utilities.
2x+3y=8 3x+y=5

solution: x=1 , y=2

Level : Medium

In [22]:
first_e = np.array([[2,3],[3,1]])
second_e = np.array([8,5])
np.linalg.solve(first_e,second_e)

array([1., 2.])

In [ ]:
9. Write a program to add two arrays of different shape.
Hint: Broadcasting

Level: Medium

sample input:

a=[0.0,10.0,20.0,30.0]

b=[1.0,2.0,3.0]

output:

[[ 1., 2., 3.],

[ 11., 12., 13.],

[ 21., 22., 23.],

[ 31., 32., 33.]]

In [23]:
a = np.array([0,10,20,30])
b = np.array([1,2,3])
a.reshape(4,1) + b.reshape(1,3)

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
10. Create a 3 * 3 array find it's diagonal using numpy utilities.¶
Level: Hard

In [25]:
data = np.random.randint(1,10,(3,3))
digonal = np.diagonal(data)
digonal

array([7, 2, 4])

In [ ]:
11. Now find anti - diagonal in previous question using horizontal and vector flip.
Level: Hard

In [ ]:
12. Create given array without using indexing.
a = [[4, 0, 0], [0, 4, 0], [0, 0, 4], [0, 0, 0], [4, 0, 0], [0, 4, 0], [0, 0, 4]]

Level : Hard

In [26]:
arr = np.identity(3)*4
zeros = np.zeros(3)
np.vstack([arr,zeros,arr])

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.],
       [0., 0., 0.],
       [4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])