In [ ]:
1. Write a NumPy program to get the numpy version and show numpy build configuration.
Level: Easy

In [2]:
import numpy as np

print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


In [ ]:
2. Create a null vector of size 10 but the fifth value which is 1.
Level: Easy

In [3]:
ten_zeroes = np.zeros(10)
ten_zeroes[4] = 1
print(ten_zeroes)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
Create a vector with values ranging from 10 to 49.
Level: Easy

In [4]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
3. create two arrays and stack them vertically
Level: Easy

In [7]:
first_array = np.arange(1,10)
second_array = np.arange(1,10)
stack_v =np.vstack([first_array,second_array])
print(stack_v)


[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [ ]:
4. Reverse a vector (first element becomes last).
Level: Easy

In [8]:
rev_vec = np.arange(5)
print(rev_vec[::-1])

[4 3 2 1 0]


In [ ]:
5. Create a 3x3 matrix with values ranging from 0 to 8
Level: Easy

In [13]:
data=np.random.randint(0,9,(3,3))

In [14]:
data

array([[7, 0, 2],
       [3, 1, 4],
       [7, 2, 2]])

In [ ]:
6. Find indices of non-zero elements from [1,2,0,0,4,0]
Level: Easy

In [19]:
arr_in = np.array([1,2,0,0,4,0])
np.nonzero(arr_in)

(array([0, 1, 4], dtype=int64),)

In [ ]:
7. Create a 10x10 array with random values and find the minimum and maximum values.

In [29]:
data  =  np.random.randint(1,1000,(10,10))
print(data)
# numpy.amax()
# numpy.amin()
np.amax(data)

[[591 271 965 976 583 121   3 748 920 204]
 [874  41 734 663 910 482 756 661  66 873]
 [939 413 779 522 850 590 982 863 192 390]
 [621 868 851 128 118 673 817 936 286 969]
 [937  36  79 127 209 263 171 559 915 600]
 [308 107 592 348 280 398 505 851 221 208]
 [435  70 188 286 692 391 733 326 373 560]
 [158 106 955 888 376 985 930 939  94 604]
 [638 516 246 669 891 182 484 259 867 804]
 [568 106 239  97 802 111 457 243 530 557]]


985

In [30]:
np.amin(data)

3

In [ ]:
8. Create a random vector of size 30 and find the mean value.
Level: Medium

In [38]:
vector=np.random.randint(1,100,(1,30,))
vector

array([[42, 17, 60, 99,  2, 49, 53, 40, 28, 96, 30, 30, 87, 80,  6, 87,
        47, 33, 25, 75, 22, 56, 67, 12, 46, 73, 48, 52, 27, 55]])

In [36]:
np.sum(vector)/30#mean

45.833333333333336

In [ ]:
9. Create a 2d array with 1 on the border and 0 inside
Level: Medium

In [100]:
oneborder = np.ones((10,10))
oneborder[1:-1, 1:-1] = 0
print(oneborder)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
10. How to add a border (filled with 0's) around an existing array
Level: Medium

In [105]:
# a = np.random.randint(1,9,(10,10))
# a[0:9,]
data=np.zeros((10,10))
data[1:-1,1:-1]=np.random.randint(1,10)
print(data)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal¶
#[[ 0. 0. 0. 0. 0.] [ 1. 0. 0. 0. 0.] [ 0. 2. 0. 0. 0.] [ 0. 0. 3. 0. 0.] [ 0. 0. 0. 4. 0.]]

In [120]:
nanu = np.zeros((5,5))
nanu[1:2,:1]=1
nanu[2:3,1:2]=2
nanu[3:4,2:3]=3
nanu[4:5,3:4]=4
print(nanu)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
12. Create a 5*5 matrix with random values and normalize it.
Level: Medium

In [127]:
mt = np.random.randint(1,100,(5,5))
mxval= mt.max()

mival = mt.min()

new= (mt-mival)/(mxval-mival)
print(new)

[[0.21111111 0.44444444 0.27777778 1.         0.14444444]
 [0.27777778 0.93333333 0.55555556 0.74444444 0.32222222]
 [0.81111111 0.3        0.         0.33333333 0.02222222]
 [0.88888889 0.2        0.5        0.17777778 0.94444444]
 [0.16666667 0.33333333 0.11111111 0.6        1.        ]]


In [ ]:
13. How to find common values between two arrays
Level: Medium

In [132]:
first = np.array([1,2,4,5])
second = np.array([1,4,5,9])
print(np.intersect1d(first,second))


[1 4 5]


In [ ]:
14. Consider a generator function that generates 10 integers and use it to build an array
Level: Medium

In [140]:
def generate(): 
    for i in range(1,11):
        yield i
        
arr = np.fromiter(generate(),dtype=float)
print (arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
15. Subtract the mean of each row of a matrix
Level: Hard

In [146]:
X = np.random.rand(5,5)
print(X)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
Y = X - X.mean(axis=1).reshape(-1, 1)


[[0.44795804 0.75321719 0.99099932 0.39808709 0.29726031]
 [0.12037089 0.04034474 0.77234913 0.72724702 0.55743142]
 [0.78107178 0.39141097 0.96658587 0.32852349 0.01062971]
 [0.51280006 0.68191149 0.88100292 0.8439078  0.55865214]
 [0.74238489 0.87508638 0.06750799 0.8842236  0.10649084]]
[[-0.12954635  0.1757128   0.41349493 -0.1794173  -0.28024408]
 [-0.32317775 -0.4032039   0.32880048  0.28369838  0.11388278]
 [ 0.28542741 -0.10423339  0.47094151 -0.16712087 -0.48501465]
 [-0.18285482 -0.01374339  0.18534804  0.14825292 -0.13700274]
 [ 0.20724615  0.33994764 -0.46763075  0.34908486 -0.4286479 ]]


In [ ]:
16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [149]:
frst = np.array([0,1,2])
scnd = np.random.randint(1,5,(3,1))


In [ ]:
17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Le

In [147]:
def generator():
    for i in range(5,51):
        if i%2==0:
            yield i
arr=np.fromiter(generator(),dtype=float)
print(arr)

[ 6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40.
 42. 44. 46. 48. 50.]
